// Code generated by mockery v2.40.1. DO NOT EDIT.

package blockchain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// blockListener is an autogenerated mock type for the blockListener type
type blockListener struct {
	mock.Mock
}

type blockListener_Expecter struct {
	mock *mock.Mock
}

func (_m *blockListener) EXPECT() *blockListener_Expecter {
	return &blockListener_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: _a0
func (_m *blockListener) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// blockListener_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type blockListener_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *blockListener_Expecter) Start(_a0 interface{}) *blockListener_Start_Call {
	return &blockListener_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *blockListener_Start_Call) Run(run func(_a0 context.Context)) *blockListener_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *blockListener_Start_Call) Return(_a0 error) *blockListener_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *blockListener_Start_Call) RunAndReturn(run func(context.Context) error) *blockListener_Start_Call {
	_c.Call.Return(run)
	return _c
}

// newBlockListener creates a new instance of blockListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBlockListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *blockListener {
	mock := &blockListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
