// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Message struct {
	TransactionHash string
	Address         string
	Token           string
	Amount          string
	Fee             string
	Content         string
	Nick            string
	AddedAt         time.Time
}

type Piggy struct {
	Address        string
	FromAddress    string
	ProfileAddress string
	CreatedAt      time.Time
	AddedAt        time.Time
	UnlocksAt      time.Time
	Name           sql.NullString
}

type Profile struct {
	Address   string
	CreatedAt time.Time
}

type Session struct {
	// randomly generated id
	ID uuid.UUID
	// blockchain address
	Address      string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}
